# Generated by Django 5.1.3 on 2024-11-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('height', models.SmallIntegerField()),
                ('weight', models.SmallIntegerField()),
                ('dnr', models.BooleanField()),
                ('insurance_check', models.BooleanField()),
            ],
        ),
    ]
