# Generated by Django 5.1.3 on 2024-11-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('medName', models.CharField(blank=True, max_length=30, null=True)),
                ('drugClass', models.CharField(blank=True, max_length=20, null=True)),
                ('adminDetails', models.CharField(blank=True, max_length=50, null=True)),
                ('storageDetails', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
