# Generated by Django 5.1.3 on 2024-11-30 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_medication'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedsTreatCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditionName', models.CharField(max_length=30)),
                ('medID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='test_app.medication')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('medID', 'conditionName'), name='unique_med_condition')],
            },
        ),
    ]
