# Generated by Django 5.1.3 on 2024-12-01 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_medstreatcondition'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medication',
            table='Medication',
        ),
        migrations.AlterModelTable(
            name='medstreatcondition',
            table=('MedsTreatCondition',),
        ),
        migrations.AlterModelTable(
            name='patient',
            table='Patient',
        ),
    ]
