# Generated by Django 5.1.3 on 2024-12-01 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_alter_medication_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medstreatcondition',
            options={'managed': False},
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='insurance_check',
            new_name='insuranceCheck',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_id',
            new_name='patientID',
        ),
    ]
