# Generated by Django 5.1.3 on 2024-12-02 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_alter_medstreatcondition_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medstreatcondition',
            table='MedsTreatCondition',
        ),
        migrations.CreateModel(
            name='FoodAllergyConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodItem', models.CharField(max_length=50)),
                ('allergy', models.CharField(max_length=30)),
                ('conflictDetails', models.TextField()),
            ],
            options={
                'db_table': 'FoodAllergyConflict',
                'unique_together': {('foodItem', 'allergy')},
            },
        ),
        migrations.CreateModel(
            name='MedAllergyConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.CharField(max_length=30)),
                ('conflictDetails', models.TextField()),
                ('medID', models.ForeignKey(db_column='medID', on_delete=django.db.models.deletion.CASCADE, to='test_app.medication')),
            ],
            options={
                'db_table': 'MedAllergyConflict',
                'unique_together': {('medID', 'allergy')},
            },
        ),
        migrations.CreateModel(
            name='MedMedConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflictDetails', models.TextField()),
                ('medID1', models.ForeignKey(db_column='medID1', on_delete=django.db.models.deletion.CASCADE, related_name='conflict_with', to='test_app.medication')),
                ('medID2', models.ForeignKey(db_column='medID2', on_delete=django.db.models.deletion.CASCADE, related_name='conflicted_by', to='test_app.medication')),
            ],
            options={
                'db_table': 'MedMedConflict',
                'unique_together': {('medID1', 'medID2')},
            },
        ),
    ]
