# Generated by Django 5.1.3 on 2024-12-02 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_alter_medstreatcondition_table_foodallergyconflict_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedMedConflict',
            new_name='MedtoMedConflict',
        ),
    ]
