# Generated by Django 5.1.3 on 2024-12-02 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_rename_medmedconflict_medtomedconflict'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medtomedconflict',
            table='MedtoMedConflict',
        ),
    ]
