# Generated by Django 5.1.3 on 2024-12-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_allergy_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medtomedconflict',
            name='conflictCheck',
        ),
        migrations.AddField(
            model_name='medtomedconflict',
            name='conflict_check',
            field=models.BooleanField(db_column='ConflictCheck', default=True),
        ),
    ]
