# Generated by Django 5.1.3 on 2024-12-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_remove_medtomedconflict_conflictcheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medications',
            field=models.ManyToManyField(blank=True, related_name='patients', to='test_app.medication'),
        ),
    ]
