# Generated by Django 5.1.3 on 2024-12-03 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_patient_medications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, max_length=15, null=True)),
                ('lastName', models.CharField(blank=True, max_length=15, null=True)),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='PatientCondition',
            fields=[
                ('medicalCondition', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('diagnosisDate', models.DateField(blank=True, null=True)),
                ('id4', models.CharField(db_column='ID4', max_length=15, primary_key=True, serialize=False)),
                ('patientID', models.ForeignKey(db_column='patientID', on_delete=django.db.models.deletion.CASCADE, to='test_app.patient')),
                ('diagnoserID', models.ForeignKey(blank=True, db_column='diagnoserID', null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.staff')),
            ],
            options={
                'db_table': 'PatientCondition',
            },
        ),
    ]
