# Generated by Django 5.1.3 on 2024-12-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_staff_patientcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], db_column='severity', max_length=10)),
                ('description', models.TextField(blank=True, db_column='description', max_length=300, null=True)),
                ('id5', models.CharField(db_column='ID5', max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PatientAllergy',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='patients', through='test_app.PatientAllergy', to='test_app.allergy'),
        ),
    ]
