# Generated by Django 5.1.3 on 2024-12-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0013_patientallergy_patient_allergies'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('dosage', models.SmallIntegerField()),
                ('admin_schedule', models.CharField(db_column='AdminSchedule', max_length=40)),
                ('id6', models.CharField(db_column='ID6', max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PatientMedication',
                'managed': False,
            },
        ),
    ]
