# Generated by Django 5.1.3 on 2024-12-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0014_patientmedication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medications',
            field=models.ManyToManyField(related_name='patients', through='test_app.PatientMedication', to='test_app.medication'),
        ),
    ]
