# Generated by Django 5.1.3 on 2024-12-03 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0015_alter_patient_medications'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationAssignment',
            fields=[
                ('assignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('dosage', models.CharField(max_length=50)),
                ('adminSchedule', models.CharField(max_length=50)),
                ('assignmentDate', models.DateField(auto_now_add=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='test_app.patientcondition')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='test_app.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='test_app.patient')),
                ('prescribingDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_medications', to='test_app.staff')),
            ],
            options={
                'db_table': 'MedicationAssignment',
            },
        ),
    ]
