# Generated by Django 5.1.3 on 2024-12-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0017_patientstaffcare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientstaffcare',
            name='id7',
            field=models.CharField(db_column='ID7', max_length=50, primary_key=True, serialize=False),
        ),
    ]
