# Generated by Django 5.1.3 on 2024-12-03 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0018_alter_patientstaffcare_id7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientstaffcare',
            name='careEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientstaffcare',
            name='careStartDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patientstaffcare',
            name='patientID',
            field=models.ForeignKey(db_column='patientID', on_delete=django.db.models.deletion.CASCADE, to='test_app.patient'),
        ),
        migrations.AlterField(
            model_name='patientstaffcare',
            name='staffID',
            field=models.ForeignKey(db_column='staffID', on_delete=django.db.models.deletion.CASCADE, to='test_app.staff'),
        ),
        migrations.AlterField(
            model_name='patientstaffcare',
            name='staffRoleInCare',
            field=models.CharField(max_length=30),
        ),
    ]
