# Generated by Django 5.1.3 on 2024-12-03 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0019_alter_patientstaffcare_careenddate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientmedication',
            options={},
        ),
    ]
