# Generated by Django 5.1.3 on 2024-12-03 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0020_alter_patientmedication_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedication',
            name='medication',
            field=models.ForeignKey(db_column='medID', default='unknown', on_delete=django.db.models.deletion.CASCADE, to='test_app.medication'),
        ),
        migrations.AddField(
            model_name='patientmedication',
            name='patient',
            field=models.ForeignKey(db_column='PatientID', default='unknown', on_delete=django.db.models.deletion.CASCADE, to='test_app.patient'),
        ),
        migrations.AddField(
            model_name='patientmedication',
            name='prescribing_doc',
            field=models.ForeignKey(db_column='prescribingDocID', default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='test_app.staff'),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='admin_schedule',
            field=models.CharField(db_column='AdminSchedule', default='Once a day', max_length=40),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='dosage',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='id6',
            field=models.CharField(db_column='ID6', default='AUTO_GEN', max_length=10, primary_key=True, serialize=False),
        ),
    ]
