# Generated by Django 5.1.3 on 2024-12-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0021_patientmedication_medication_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicationAssignment',
        ),
    ]
