# Generated by Django 5.1.3 on 2024-12-03 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0022_delete_medicationassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPhone',
            fields=[
                ('phone', models.CharField(db_column='phone', max_length=15)),
                ('id8', models.CharField(db_column='ID8', max_length=15, primary_key=True, serialize=False)),
                ('staffID', models.ForeignKey(db_column='staffID', on_delete=django.db.models.deletion.CASCADE, to='test_app.staff')),
            ],
            options={
                'db_table': 'StaffPhone',
            },
        ),
    ]
